version: '3.1'

services:
  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  postgres_atmos:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: atmos_db
      POSTGRES_USER: atmos
      POSTGRES_PASSWORD: atmos
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./create_table.sql:/docker-entrypoint-initdb.d/dump.sql
