version: '3.1'

services:
  postgres_atmos:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: atmos_db
      POSTGRES_USER: atmos
      POSTGRES_PASSWORD: atmos
      POSTGRES_HOST: localhost
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./create_table.sql:/docker-entrypoint-initdb.d/dump.sql
